### ISSUE TITLE
Unhelpful completion suggestion in .xsl file.

### ISSUE THREAD

**Issue by expez** [aki2o/auto-complete-nxml#2]
Hi, I'm using XSLT to generate HTML.  I'm often in a situation similar to this:

``` html
<div class="foo"|
```

where | indicates the cursor.  When I now hit space, to add another attribute, 'xsl:' is automatically inserted.  This is not helpful when I want to write 'id=..' :)

Otherwise, thanks for a wonderful mode.  I wrote a recipe for MELPA, and it got accepted yesterday, so that is now an alternative to using el-get.  Let me know if you want me to add installation instructions, for MELPA, to the README.

**Comment by aki2o** [comment]
Hi, @expez 

The candidate, which auto-complete-nxml.el show, is generated by the function of nXML-mode.
Would you please do "nxml-complete" at where you want to do completion?
I tested it in this issue case and "id" was not shown.

So, this issue is caused by nXML-mode.
The following message was shown.when I opened a XSLT file.

```
Using schema c:/App/emacs/etc/schema/xslt.rnc
```

I guess the definition about html not exist in the above scheme.

>  I wrote a recipe for MELPA

I had known your help and I appreciate your help.
I updated README about MELPA.

**Comment by expez** [comment]
If I have 

``` html
<div class="row" |>
```

where | indicates the cursor and do 'nxml-complete' I get:

``` html
<div class="row" xsl:>
```

In other words you are right, nxml-mode is to blame, but how can I fix this?  I don't think I can have multiple schemas active at the same time.  Can I get nxml-mode to just be quiet when it doesn't know what it's talking about?

**Comment by aki2o** [comment]
I added the function that user can toggle on/off automatic completion.
Please see README.
Can you resolve this issue by this function?

**Comment by expez** [comment]
I was hoping this could be handled automatically, somehow, but this is good enough.  Thanks for your help!

**Comment by aki2o** [comment]
> I was hoping this could be handled automatically

I also wanted to do so.

> Thanks for your help!

Thanks for your feedback, too.
